boards/urls.py
from django.conf.urls import url

import django.contrib.auth.views
from . import views

app_name = 'boards'
urlpatterns = [
    url(r'^$', views.start, name='start'),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^boards/$', views.index, name='index'),
      # ex: /boards/5/lists
    url(r'^(?P<board_id>[0-9]+)/lists/$', views.board_content, name='board_content'),
    # ex: /boards/5/lists/1
    url(r'^(?P<board_id>[0-9]+)/lists/(?P<list_id>[0-9]+)/$', views.list_content, name='list_content'),
    url(r'^(?P<board_id>[0-9]+)/lists/(?P<list_id>[0-9]+)/tasks/(?P<task_id>[0-9]+)/$', views.task_content, name='task_content'),
    url(r'^new/$', views.board_new, name='board_new'),
    url(r'^(?P<board_id>[0-9]+)/lists/new/$', views.list_new, name='list_new'),
    url(r'^(?P<board_id>[0-9]+)/lists/(?P<list_id>[0-9]+)/task_new/$', views.task_new, name='task_new'),
    url(r'^(?P<board_id>[0-9]+)/lists/edit/$', views.board_edit, name='board_edit'),
    url(r'^(?P<board_id>[0-9]+)/lists/(?P<list_id>[0-9]+)/edit/$', views.list_edit, name='list_edit'),
    url(r'^(?P<board_id>[0-9]+)/lists/remove/$', views.board_remove, name='board_remove'),
    url(r'^(?P<board_id>[0-9]+)/lists/(?P<list_id>[0-9]+)/remove/$', views.list_remove, name='list_remove'),
    url(r'^(?P<board_id>[0-9]+)/lists/(?P<list_id>[0-9]+)/tasks/(?P<task_id>[0-9]+)/remove/$', views.task_remove, name='task_remove'),
    url(r'^(?P<board_id>[0-9]+)/lists/(?P<list_id>[0-9]+)/tasks/(?P<task_id>[0-9]+)/edit/$', views.task_edit, name='task_edit'),
    url(r'^(?P<board_id>[0-9]+)/lists/(?P<list_id>[0-9]+)/tasks/(?P<task_id>[0-9]+)/comment/$', views.add_comment_to_task, name='add_comment_to_task'),
    # ex: /polls/5/vote/
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

trello/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'', include('boards.urls')),
#    url(r'^boards/', include('boards.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
]

boards/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from datetime import datetime
from django.db import models
from django.conf import settings

class Board(models.Model):
    board_name = models.CharField(max_length=200)
    creation_date = models.DateTimeField('date of creation', default=datetime.now, blank=True)
    def __str__(self):
        return self.board_name

class List(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    list_name = models.CharField(max_length=200)
    def __str__(self):
        return self.list_name

class Task(models.Model):
    task_list = models.ForeignKey(List, on_delete=models.CASCADE)
    task_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
#    deadline = models.DateTimeField('due date')
    deadline = models.DateTimeField(default=datetime.now)
    executor = models.ForeignKey(User)
    def __str__(self):
        return self.task_text

class Comment(models.Model):
    task = models.ForeignKey(Task, related_name='comments', default = '')
#    author = models.ForeignKey(User)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
    )
    text = models.CharField(max_length=500)
    created_date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.text

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

boards/forms.py
from django import forms
from .models import Board, List, Task, Comment, User
from django.utils.translation import ugettext_lazy as _

class BoardForm(forms.ModelForm):

    class Meta:
        model = Board
        fields = ('board_name',)

class ListForm(forms.ModelForm):

    class Meta:
        model = List
        fields = ('list_name',)

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('task_text', 'deadline', 'executor',)
        ordering = ['-deadline']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

class RegistrationForm(forms.Form):

    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password (again)"))

boards/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.http import HttpResponse
from datetime import datetime
from django import forms
from django.contrib.auth.models import User
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate
from .models import Board, List, Task, Comment
from .forms import BoardForm, ListForm, TaskForm, CommentForm

def start(request):
    return render(request, 'boards/base.html', {})


def index(request):
    boards = Board.objects.order_by('-creation_date')[:10]
    context = {
        'boards': boards,
    }
    return render(request, 'boards/index.html', context)


def board_content(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    tasks = Task.objects.order_by('-deadline')
    return render(request, 'boards/board_content.html', {'board': board})    

def list_content(request, board_id, list_id):
    list = get_object_or_404(List, pk=list_id)
    board = get_object_or_404(Board, pk=board_id)
    tasks = Task.objects.order_by('-deadline')
    return render(request, 'boards/list_content.html', {'board': board, 'list': list, 'tasks' : tasks})

def task_content(request, board_id, list_id, task_id):
#    task = Task.objects.order_by('-deadline')
    task = get_object_or_404(Task, pk=task_id)
    list = get_object_or_404(List, pk=list_id)
    board = get_object_or_404(Board, pk=board_id)
    return render(request, 'boards/task_content.html', {'board': board, 'list': list, 'task': task})


def board_new(request):
    if request.method == "POST":
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.creation_date = datetime.now()
            board.save()
            return redirect('/%s/lists/' %board.pk, pk=board.pk)
    else:
        form = BoardForm()
    return render(request, 'boards/board_new.html', {'form': form})

def list_new(request, board_id):
    if request.method == "POST":
        form = ListForm(request.POST)
        if form.is_valid():
            list = form.save(commit=False)
            board = get_object_or_404(Board, pk=board_id)
            list.board = board
            list.save()
            page = '/' + str(board_id) + '/lists/'
            return redirect(page, pk = list.pk)
    else:
        form = ListForm()
    return render(request, 'boards/list_new.html', {'form': form})

def task_new(request, board_id, list_id):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.pub_date = datetime.now()
            task_list = get_object_or_404(List, pk=list_id)
            task.task_list = task_list
            task.save()
            page = '/' + str(board_id) + '/lists/' + str(list_id)
            return redirect(page, pk = task.pk)
    else:
            form = TaskForm()
    return render(request, 'boards/task_new.html', {'form': form})

def board_edit(request, board_id):
        board = get_object_or_404(Board, pk=board_id)
        if request.method == "POST":
            form = BoardForm(request.POST, instance=board)
            if form.is_valid():
                board = form.save(commit=False)
                board.creation_date = datetime.now()
                board.save()
                return redirect('/%s/lists/' %board.pk, pk=board.pk)
        else:
            form = BoardForm(instance=board)
        return render(request, 'boards/board_edit.html', {'form': form})

def list_edit(request, board_id, list_id):
        list = get_object_or_404(List, pk=list_id)

        if request.method == "POST":
            form = ListForm(request.POST, instance=list)
            if form.is_valid():
                list = form.save(commit=False)
                board = get_object_or_404(Board, pk=board_id)
                list.board = board
                list.save()
                page = '/' + str(board_id) + '/lists/' + str(list_id)
                return redirect(page, pk=list.pk)
        else:
            form = ListForm(instance=list)
        return render(request, 'boards/list_edit.html', {'form': form})

def task_edit(request, board_id, list_id, task_id):
        task = get_object_or_404(Task, pk=task_id)

        if request.method == "POST":
            form = TaskForm(request.POST, instance=task)
            if form.is_valid():
                task = form.save(commit=False)
                task_list = get_object_or_404(List, pk=list_id)
                task.pub_date = datetime.now()
                task.task_list = task_list
                task.save()
                page = '/' + str(board_id) + '/lists/' + str(list_id) + '/tasks/' + str(task_id)
                return redirect(page, pk=task.pk)
        else:
            form = TaskForm(instance=task)
        return render(request, 'boards/task_edit.html', {'form': form})

def board_remove(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    board.delete()
    return redirect('/boards/')

def list_remove(request, board_id, list_id):
    list = get_object_or_404(List, pk=list_id)
    list.delete()
    return redirect('/%s/lists/' %board_id)

def task_remove(request, board_id, list_id, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.delete()
    page = '/' + str(board_id) + '/lists/' + str(list_id)
    return redirect(page)

def add_comment_to_task(request, board_id, list_id, task_id):
    task = get_object_or_404(Task, pk=task_id)
    author = request.user
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.task = task
            comment.author = author
            comment.created_date = datetime.now()
            comment.save()
            page = '/' + str(board_id) + '/lists/' + str(list_id) + '/tasks/' + str(task_id)
            return redirect(page)
    else:
        form = CommentForm()
    return render(request, 'boards/add_comment_to_task.html', {'form': form})


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/"
    template_name = "register.html"

    def form_valid(self, form):
        form.save()
        new_user = authenticate(username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'])
        login(self.request, new_user)
        return super(RegisterFormView, self).form_valid(form)

boards/templates/boards/add_comment_to_task.html
<body style="background:#E5E4E2">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
{% block content %}
    <ul><h1>New comment</h1></ul>
    <ul>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Send</button>
    </ul>
    </form>
{% endblock %}
</body>

boards/templates/boards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Welcome!</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<style>
body {margin:25px;}
div.polaroid {
  width: 100%;
  background-color: #C0C0C0;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 10px 6px 12px 10px rgba(0, 0, 0, 0.19);
  margin-bottom: 25px;
}

div.container {
  text-align: center;
  padding: 10px 20px;
}
</style>

</head>
<body style="background:#E5E4E2">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{%url 'boards:index' %}">Tracker</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{%url 'boards:login' %}">Log in</a></li>
    </ul>
  </div>
</nav>

<div class="container">
	  <h1>Welcome to Tracker!</h1>
          <div class="container">
	  <h4>Thank you for using this tracking system. We offer you a lot of advanced features which will help you to reach your goals.</h4>
          </div>
  <h2><a href = "{%url 'boards:register' %}" style="color:green"><u>Create an account</u></a></h2>
  <h2><a href="{%url 'boards:login' %}" style="color:green"><u>Log in</u></a></h2>
</div>

<div class="container">
 <h2>How does it work?</h2> 
            This is a Tracker board. It’s a list of lists filled with cards, used
            with a team or by yourself.
 
            Drag and drop cards between lists to show progress.
            Add as many people as you need and drag them to cards.
            Add and reorder lists as you need. <strong>Tracker
            adapts to your project, team, and workflow.</strong>

            You’ll see everything about your project just by glancing at the
            board, and it all updates in real-time. There’s nothing to set up
            and everyone gets it instantly.
 </p>
</div>
	
<div class="container">
      <div class="polaroid">
        <img src="https://pp.vk.me/c637418/v637418472/102d2/WUB4H4BRHuU.jpg" alt="Board" align="middle" style="width:100%">
        <p><strong>A Tracker board is a list of lists filled with tasks.</strong> </p>
  </div>
</div>

</body>
</html>

boards/templates/boards/board_content.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'boards/style.css' %}" />

<style type="text/css">
 .topcorner{
   position:absolute;
   top:0;
   right:0;
  }
</style>
<body style="background:#E5E4E2">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Tracker</a>
    </div>
  <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:index' %}">Boards</a></li>
  </ul>
   <ul class="nav navbar-nav">
    <li class="active"><a href="#">{{ board.board_name }}</a></li>
  </ul>
  <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:board_edit' board.id %}"><span class="glyphicon glyphicon-pencil"></span></a></li>
  </ul>
  <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:board_remove' board.id %}"><span class="glyphicon glyphicon-remove"></span></a></li>
  </ul>
 <ul class="nav navbar-nav navbar-right">
    <li><a>{{user.get_username}}</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="{%url 'boards:logout' %}">Log out</a></li>
  </ul>
  </div>
</nav>

<ul><h1>{{ board.board_name }}<a href="{% url 'boards:list_new' board.id %}"> <span class="glyphicon glyphicon-plus" style="color:green"></span></a>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</h1></ul>

{% for list in board.list_set.all %}
    <div class = "col-md-3">
    <h4><a href="{%url 'boards:list_content' board.id list.id %}">{{ list.list_name }}</a></h4>
    {% if list.task_set.all %}
        {% for task in list.task_set.all %}
           <div class="alert alert-success">
           <a href="{% url 'boards:task_content' board.id list.id task.id%}">{{ task.task_text }}</a>
           <div class ="date"><u> Due date:</u> <mark style="background-color:#F6D8CE">{{ task.deadline}}</mark></div>
           {% if task.comments.count %}
               Comments: {{ task.comments.count }}
            {% endif %}
            </div>
        {% endfor %}
        </div>
        </div>
    {% else %}
        <ul>This list is empty.</ul>
    {% endif %}
{% endfor %}
<div class="col-md-4">
</body>

boards/templates/boards/board_edit.html
<body style="background:#E5E4E2">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Tracker</a>
    </div>
  <ul class="nav navbar-nav">
    <li><a href="{%url 'boards:index' %}">Boards</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="{%url 'boards:logout' %}">Log out</a></li>
  </ul>
  </div>
</nav>

{% block content %}
       <h1>Edit board</h1>
       <ul>
       <form method="POST" class="post-form">{% csrf_token %}
           {{ form.as_p }}
           <button type="submit" class="btn btn-success">Save</button>
       </ul>
       </form>
{% endblock %}
</body>

boards/templates/boards/board_new.html
<body style="background:#E5E4E2">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Tracker</a>
    </div>
  <ul class="nav navbar-nav">
    <li><a href="{%url 'boards:index' %}">Boards</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="{%url 'boards:logout' %}">Log out</a></li>
  </ul>
  </div>
</nav>
{% block content %}
       <h1>New board</h1>
       <ul>
       <form method="POST" class="post-form">{% csrf_token %}
           {{ form.as_p }}
           <button type="submit" class="btn btn-success">Save</button>
       </ul>
       </form>
{% endblock %}
</body>

boards/templates/boards/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'boards/style.css' %}" />

<body style="background:#E5E4E2">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Tracker</a>
    </div>
  <ul class="nav navbar-nav">
    <li class="active"><a href="#">Boards</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a>{{user.get_username}}</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="{%url 'boards:logout' %}">Log out</a></li>
  </ul>
  </div>
</nav>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% if boards %}
    <ul>
    {% for board in boards %}
        <li><a href="{% url 'boards:board_content' board.id %}">{{ board.board_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <ul><p>No boards are available.</p></ul>
{% endif %}
<ul><a href="{% url 'boards:board_new' %}" button type="submit" class="btn btn-success">Add a new board</a></ul>
</body>

boards/templates/boards/list_content.html
<body style="background:#E5E4E2">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Tracker</a>
    </div>
  <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:index' %}">Boards</a></li>
  </ul>
   <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:board_content' board.id %}">{{ board.board_name }}</a></li>
  </ul>
   <ul class="nav navbar-nav">
    <li class="active"><a href="#">{{ list.list_name }}</a></li>
  </ul>
  <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:list_edit' board.id list.id%}"><span class="glyphicon glyphicon-pencil"></span></a></li>
  </ul>
  <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:list_remove' board.id list.id%}"><span class="glyphicon glyphicon-remove"></span></a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="{%url 'boards:logout' %}">Log out</a></li>
  </ul>
  </div>
</nav>


<ul><h1>{{ list.list_name }}</ul>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

</h1>
<ul>
{% for task in list.task_set.all %}
    <li><a style=color:green href="{%url 'boards:task_content' board.id list.id task.id %}"><h4>{{ task.task_text }}</h4></a></li>
    <div class ="date"><u> Due date:</u> <mark style="background-color:#F6D8CE">{{ task.deadline}}</mark></div>
{% endfor %}
<a href="{%url 'boards:task_new' board.id list.id %}" button type="submit" class="btn btn-success">Add a new task</a>
</ul>
</body>

boards/templates/boards/list_edit.html
<body style="background:#E5E4E2">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
{% block content %}
       <h1>Edit list</h1>
       <ul>
       <form method="POST" class="post-form">{% csrf_token %}
           {{ form.as_p }}
           <button type="submit" class="btn btn-success">Save</button>
       </ul>
       </form>
{% endblock %}
</body>

boards/templates/boards/list_new.html
<body style="background:#E5E4E2">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Tracker</a>
    </div>
  <ul class="nav navbar-nav">
    <li><a href="{%url 'boards:index' %}">Boards</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="{%url 'boards:logout' %}">Log out</a></li>
  </ul>
  </div>
</nav>

{% block content %}
       <h1>New list</h1>
       <ul>
       <form method="POST" class="post-form">{% csrf_token %}
           {{ form.as_p }}
           <button type="submit" class="btn btn-success">Save</button>
       </ul>
       </form>
{% endblock %}
</body>

boards/templates/boards/register.html
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{ form }}
  <div class="submit-button">
    <button type="submit">Register</button>
  </div>
</form>
{% endblock %}

boards/templates/boards/task_content.html
{% load staticfiles %}
<head>
<style>
  mark {
    background-color: blue;
}
</style>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background:#E5E4E2">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Tracker</a>
    </div>
  <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:index' %}">Boards</a></li>
  </ul>
   <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:board_content' board.id %}">{{ board.board_name }}</a></li>
  </ul>
   <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:list_content' board.id list.id %}">{{ list.list_name }}</a></li>
  </ul>
  <ul class="nav navbar-nav">
    <li class="active"><a href="#">{{ task.task_text }}</a></li>
  </ul>
  <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:task_edit' board.id list.id task.id %}"><span class="glyphicon glyphicon-pencil"></span></a></li>
  </ul>
  <ul class="nav navbar-nav">
    <li><a href="{% url 'boards:task_remove' board.id list.id task.id %}"><span class="glyphicon glyphicon-remove"></span></a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="{%url 'boards:logout' %}">Log out</a></li>
  </ul>
  </div>
</nav>


<ul><h1>{{ task.task_text }}</ul>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
</h1>
<ul><div class ="date"><u>Due date:</u><mark style="background-color:#F6D8CE"> {{ task.deadline}}</mark></div></ul>
<ul><u>Executor:</u> {{task.executor}}</ul>
<ul>
    <h4>Comments ({{task.comments.count}}) <a href="{% url 'boards:add_comment_to_task' board.id list.id task.id %}"><span class="glyphicon glyphicon-plus" style="color:green"></span></a></h4>
    {% for comment in task.comments.all %}
        <hr>
        <ul>
        <div class="comment">
            <div class="date">{{ comment.created_date }}</div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        </ul>
        <hr>
    {% endfor %}
</ul>
</body>